id = "amber"
name = "Amber"
description = "Amber Language support."
version = "0.3.2"
schema_version = 1
authors = ["Paweł Karaś <pkaras.it@gmail.com>", "Hubert Jabłoński <hubik080@gmail.com>"]
repository = "https://github.com/Ph0enixKM/zed-amber-extension"

[grammars.amber]
repository = "https://github.com/amber-lang/tree-sitter-amber"
commit = "dc69f42449fd3c807bacefa398263f62e581f755"

[language_servers.amber]
name = "Amber Language Server"
language = "Amber"
