id = "amber"
name = "Amber"
description = "Amber Language support."
version = "0.1.2"
schema_version = 1
authors = ["Paweł Karaś <pkaras.it@gmail.com>", "Hubert Jabłoński <hubik080@gmail.com>"]
repository = "https://github.com/Ph0enixKM/zed-amber-extension"

[grammars.amber]
repository = "https://github.com/amber-lang/tree-sitter-amber"
commit = "cafa15e6224fcb43cc88275e1afaf33179a4f393"

[language_servers.amber]
name = "Amber Language Server"
language = "Amber"
